### ISSUE TITLE
Travis shouldn't install conda dependencies if doing a tagged release

### ISSUE THREAD

**Issue by matt-chan** [theochem/cgrid#29]
It looks like the install in .travis.yml 106-118 isn't necessary in a tagged release. Since we use conda build on tagged releases, everything should be installed in its own build root. Installing the dependencies otherwise should only be a waste of time. 
```
- conda render tools/conda.recipe > tools/conda.recipe/rendered.yaml
- conda render ${PYDIR}/tools/conda.recipe > ${PYDIR}/tools/conda.recipe/rendered.yaml
- CONDA_DEPENDENCIES=$(python -c "from yaml import load;
    req1 = load(open('tools/conda.recipe/rendered.yaml'))['requirements'];
    req2 = load(open('${PYDIR}/tools/conda.recipe/rendered.yaml'))['requirements'];
    deps = req1['build'] + req1['run'] + req2['build'] + req2['run'];
    print(' '.join(set(dep.split()[0] for dep in deps if not dep.startswith('${CONDA_PKG_NAME_CPP}'))))")

- conda install -q python=${MYCONDAPY} cppcheck doxygen anaconda-client ${CONDA_DEPENDENCIES}
```

**Comment by tovrstra** [comment]
Agreed

**Comment by tovrstra** [comment]
This has become outdated.

Roberto takes care of building and packaging. It does still do everything when testing the master branch. While this is overkill in most cases, it does occasionally reveal issues that would otherwise be noticed very lated.
